"""Default values for Supreme Diffusion configuration."""

from pathlib import Path

# App root = repo directory (where run.py lives)
APP_ROOT = Path(__file__).resolve().parent.parent.parent

# Factory directories inside the install directory
_MODELS = APP_ROOT / "models"
_PROJECTS = APP_ROOT / "projects"
_LIBRARY = APP_ROOT / "library"

GLOBAL_DEFAULTS = {
    "model_paths": {
        "transformer": "",
        "transformer_2": "",
        "vae": "",
        "text_encoder": "",
        "image_encoder": "",
        "lora_dir": str(_MODELS / "loras" / "wan"),
        "sd_checkpoint_dir": str(_MODELS / "checkpoints"),
        "sd_refiner_dir": str(_MODELS / "refiners"),
        "sd_vae_dir": str(_MODELS / "vae"),
        "sd_lora_dir": str(_MODELS / "loras" / "sd"),
        "face_models_dir": str(_MODELS / "face"),
        "flux_chroma_dir": "",
        "flux_fill_dir": "",
        "flux_gguf_dir": str(_MODELS / "flux"),
        "flux_lora_dir": str(_MODELS / "loras" / "flux"),
        "birefnet_dir": str(_MODELS / "birefnet"),
        "zimage_dir": str(_MODELS / "zimage"),
        "zimage_lora_dir": str(_MODELS / "loras" / "zimage"),
        "upscaler_dir": str(_MODELS / "upscalers"),
        # RIFE frame-interpolation weights. Empty = auto-discover (rife_pipeline
        # falls back to ffmpeg minterpolate when unset/missing).
        "rife_model": "",
        "ltx_transformer": "",
        "ltx_vae": "",
        "ltx_text_encoder": "",
        "ltx_embeddings_connector": "",
        "ltx_text_projection": "",
        "ltx_lora_dir": str(_MODELS / "loras" / "ltx"),
        "ltx_spatial_upsampler": "",
        "ltx_temporal_upsampler": "",
        # MimicMotion: SVD-XT base + motion module. Default to symlinked /data/MimicMotion.
        "mimicmotion_dir": str(_MODELS / "mimicmotion"),
        "mimicmotion_svd_subdir": "svd-xt-1-1",
        "mimicmotion_motion_subdir": "motion_module",
    },
    "attention_mode": "xformers",
    "memory_profile": 4,
    "text_encoder_quantization": "int8",
    "vae_precision": "16",
    "enable_int8_kernels": False,
    # Performance settings (matching wan2gp Performance tab)
    "transformer_quantization": "int8",
    "transformer_dtype_policy": "",
    "mixed_precision": "0",
    "lm_decoder_engine": "",
    "compile_transformer": "",
    "vae_tiling": 0,
    "boost": 2,
    "preload_in_vram": 0,
    "max_reserved_loras": -1,
    "denoising_loop": "standard",
    "video_output_codec": "libx264",
    "video_container": "mp4",
    # Project-level color profile slug (matches keys in color_profile._PRESETS).
    # Default = bt709_limited which mirrors the existing GODOT_COLOR_ARGS
    # (yuv420p + tv-range + bt709) so legacy projects keep playing in Godot
    # exactly the way they always have.
    "default_color_profile": "bt709_limited",
    "projects_root": str(_PROJECTS),
    "png_library_dir": str(_LIBRARY / "png"),
    "face_library_dir": str(_LIBRARY / "faces"),
    "characters_dir": str(_LIBRARY / "characters"),
    "meshes_dir": str(_LIBRARY / "meshes"),
    "models_root": str(_MODELS),
    "audio_device": "",
    "last_project": "",
    "last_parent_tab_idx": 0,
    "last_video_tab_idx": 0,
    "quality_tier": "auto",  # auto | draft | standard | production | ultra
    "ui_layout": "classic",  # classic | modern
    "last_sidebar_key": "",
    "tl_clip_zoom": 80,  # timeline pixels-per-second (10–500)
    # Color drift neutralization — applied to frames extracted from prior
    # generations before they become conditioning inputs for the next clip.
    # Breaks the compound-orange chain when chaining LTX/Wan generations.
    "neutralize_frames_enabled": False,
    "neutralize_reference_path": "",  # optional anchor; empty = gray-world
    "neutralize_strength": 1.0,
}

PROJECT_DEFAULTS = {
    "last_parent_tab": "",
    "last_child_tab": "",
    "mode": 1,
    # Input file paths (remembered per project)
    "image_path": "",
    "first_frame_path": "",
    "last_frame_path": "",
    "guidance_video_path_m1": "",
    "guidance_video_path_m2": "",
    "m3_video_path": "",
    "preview_path_m1": "",
    "preview_path_m2": "",
    "ve_preview_path": "",
    "ve_video_path": "",
    "ve_last_frame_path": "",
    "ve_guidance_video_path": "",
    "ve_guidance_video_frame": "0",
    "ltx_inpaint_mask_path": "",
    "ltx_control_type": "",
    "ltx_control_strength": 1.0,
    "ltx_control_start_seconds": 0.0,
    "ltx_control_ramp_frames": 0,
    "ltx_audio_path": "",
    "video_backend": "wan",
    "model_type": "i2v_2_2_lightning_v2",
    "resolution": "512x512",
    "fps": 16,
    "video_length": 81,
    "prompt": "",
    "negative_prompt": "",
    "num_inference_steps": 4,
    "guidance_scale": 1.0,
    "guidance2_scale": 1.0,
    "alt_guidance_scale": 1.0,
    "guidance_phases": 2,
    "switch_threshold": 900,
    "flow_shift": 5.0,
    "sample_solver": "unipc",
    "seed": -1,
    "denoising_strength": 1.0,
    "masking_strength": 0.0,
    "activated_loras": [],
    "loras_multipliers": "",
    "NAG_scale": 0.0,
    "NAG_tau": 0.0,
    "NAG_alpha": 0.0,
    "cfg_star_switch": 0,
    "cfg_zero_step": 0,
    "tea_cache_setting": "off",
    "tea_cache_start_step_perc": 0.0,
    "use_guidance_m1": False,
    "generate_static_m1": True,
    "use_guidance_m2": False,
    "generate_static_m2": True,
    "guidance_video_source": "none",
    "guidance_video_frame": "first",
    # Quality / Advanced enable gates
    "quality_overrides_enabled": False,
    "nag_tea_enabled": False,
    # Quality settings
    "slg_switch": 0,
    "slg_layers": [],
    "slg_start_perc": 0,
    "slg_end_perc": 100,
    "apg_switch": 0,
    "motion_amplitude": 1.0,
    "self_refiner_setting": 0,
    "self_refiner_uncertainty": 0.0,
    "self_refiner_certainty_skip": 0.999,
    # Discard last frames
    "discard_last_frames": 0,
    # Color correction
    "color_correction_strength": 0.0,
    # Color-match method — see supremediffusion.utils.color_correct.COLOR_MATCH_METHODS.
    # Default mean-only-lab is drift-resistant (right for chained continuations).
    # Switch to hm-mvgd-hm for strong single-shot match-to-source — eliminates
    # the need for post-hoc timeline grading on most generations.
    "color_correction_method": "mean-only-lab",
    # How much of color_correction_strength holds across the whole clip vs
    # fading to zero. Legacy fade-to-zero (persistence=0) let VAE warm bias
    # re-accumulate by frame ~24. Default 0.6 = 60% strength held throughout
    # the clip so drift can't sneak back in mid-shot.
    "color_anchor_persistence": 0.6,
    # Pre-match stage strength — independent of color_correction_strength so the
    # pre-match (source-anchored) pass can be tuned separately from the per-frame
    # anchor strength. Was hardcoded 0.8 in pipeline.py pre-match.
    "anchor_prematch_strength": 0.8,
    # Wan 2.2 LoRA presets — auto-load Lightning / SVI Pro LoRAs and adjust
    # sampler params. Values match supremediffusion.models.wan_presets.
    # off / lightning_4step / lightning_6step
    "acceleration_preset": "off",
    # off / svi_pro
    "antidrift_preset": "off",
    # Post-processing pipeline (Phase 3 — unified Quality preset).
    # draft / standard / quality / master — see workers/post_pipeline.py
    "output_quality": "standard",
    # Specific upscaler model filename inside chkpts/upscalers/. Empty = default 4x-UltraSharp.pth.
    "upscale_model": "4x-UltraSharp.pth",
    # Frame interpolation multiplier for Master preset.
    "rife_multiplier": 2.0,
    # SVI 2 Pro — Sliding Window + Anchor Image
    # Defaults match wan2gp's i2v_2_2_Enhanced_Lightning_v2_svi2pro_settings.json
    "sliding_window_size": 81,
    "sliding_window_overlap": 4,
    "sliding_window_color_correction_strength": 0.0,
    "sliding_window_overlap_noise": 0.0,
    "sliding_window_discard_last_frames": 0,
    "anchor_image_mode": "start",   # "start" | "single" | "per_window"
    "anchor_image_path": "",         # single image OR ";"-separated for per_window
    # Post-processing
    "temporal_upsampling": "",
    "spatial_upsampling": "",
    "film_grain_intensity": 0.0,
    "film_grain_saturation": 0.5,
    # Trim / Crop persisted paths
    "tc_source_path": "",
    "trim_video_path": "",
    "crop_video_path": "",
    # Image suite source image paths
    "img2img_source_path": "",
    "inpaint_source_path": "",
    "imgedit_source_path": "",
    "cropzoom_source_path": "",
    # Image generation settings
    "selected_image_model_filename": "",
    "selected_image_model_type": "",
    "selected_image_model_subtype": "",
    "img_checkpoint": "",
    "img_vae": "Automatic",
    # SD VAE precision — "16" (fp16, default) or "32" (fp32 escape for the
    # classic SDXL fp16-VAE black-image / NaN bug).
    "sd_vae_precision": "16",
    "img_sampler": "DPM++ 2M",
    "img_scheduler": "Karras",
    "img_steps": 20,
    "img_cfg_scale": 7.0,
    "img_width": 512,
    "img_height": 512,
    "img_seed": -1,
    "img_batch_size": 1,
    "img_batch_count": 1,
    "img_prompt": "",
    "img_negative_prompt": "",
    "img_denoising_strength": 0.75,
    "img_ipadapter_path": "",
    "img_ipadapter_scale": 0.0,
    "img_ipadapter_variant": "plus",
    "img_resize_mode": 0,
    "img_mask_blur": 4,
    "img_inpainting_fill": 1,
    "img_mask_invert": False,
    # Phase 4b: optional Laplacian pyramid blend on inpaint composite for
    # seam-free paste-back. False = legacy PIL.Image.composite alpha blend.
    "img_inpaint_laplacian_blend": False,
    "img_inpaint_full_res": False,
    "img_inpaint_full_res_padding": 32,
    "img_clip_skip": 1,
    "img_loras": [],
    "img_lora_multipliers": "",
    # SDXL Refiner settings
    "img_refiner_enabled": False,
    "img_refiner_checkpoint": "",
    "img_refiner_switch_at": 0.8,
    "img_refiner_steps": 10,
    "img_refiner_cfg_scale": 7.0,
    # Face swap settings
    "faceswap_source_path": "",
    "faceswap_target_path": "",
    "faceswap_model": "inswapper_128",
    "faceswap_enhancer": "None",
    "faceswap_blend_ratio": 0.5,
    "faceswap_source_face_idx": 0,
    "faceswap_target_face_idx": 0,
    "faceswap_swap_all": False,
    "faceswap_enhancer_strength": 0.5,
    "faceswap_enhance_source": False,
    # ADetailer (post-gen face refinement)
    "adetailer_enabled": False,
    "adetailer_detector": "insightface",
    "adetailer_threshold": 0.30,
    "adetailer_dilation_pct": 20.0,
    "adetailer_feather_px": 12,
    "adetailer_denoise": 0.40,
    "adetailer_steps_add": 6,
    "adetailer_inpaint_size": 1024,
    "adetailer_prompt_override": "",
    "adetailer_neg_prompt_override": "",
    # Body Double settings
    "bodydouble_checkpoint": "",
    "bodydouble_sampler": "DPM++ 3M SDE",
    "bodydouble_scheduler": "Karras",
    "bodydouble_source_path": "",
    "bodydouble_target_path": "",
    "bodydouble_prompt": "",
    "bodydouble_negative_prompt": "",
    "bodydouble_steps": 30,
    "bodydouble_cfg_scale": 7.5,
    "bodydouble_seed": -1,
    "bodydouble_denoising_strength": 0.85,
    "bodydouble_controlnet_strength": 0.7,
    "bodydouble_ip_adapter_scale": 0.6,
    "bodydouble_mask_blur": 8,
    "bodydouble_mask_path": "",
    "bodydouble_controlnet_type": "openpose",
    "bodydouble_controlnet2_type": "",
    "bodydouble_controlnet2_strength": 0.5,
    "bodydouble_ip_adapter_variant": "plus",
    "bodydouble_width": 0,
    "bodydouble_height": 0,
    "bodydouble_guidance_start": 0.0,
    "bodydouble_guidance_end": 1.0,
    "bodydouble_clip_skip": 1,
    "bodydouble_style_preset": "balanced",
    "bodydouble_ip_adapter2_variant": "",
    "bodydouble_ip_adapter2_scale": 0.5,
    "bodydouble_style_ref_path": "",
    # RePose settings
    "repose_checkpoint": "",
    "repose_sampler": "DPM++ 3M SDE",
    "repose_scheduler": "Karras",
    "repose_source_path": "",
    "repose_pose_path": "",
    "repose_prompt": "",
    "repose_negative_prompt": "",
    "repose_steps": 30,
    "repose_cfg_scale": 7.5,
    "repose_seed": -1,
    "repose_denoising_strength": 0.85,
    "repose_controlnet_strength": 0.7,
    "repose_ip_adapter_scale": 0.6,
    "repose_mask_blur": 8,
    "repose_mask_path": "",
    "repose_controlnet_type": "openpose",
    "repose_controlnet2_type": "",
    "repose_controlnet2_strength": 0.5,
    "repose_ip_adapter_variant": "plus",
    "repose_width": 0,
    "repose_height": 0,
    "repose_guidance_start": 0.0,
    "repose_guidance_end": 1.0,
    "repose_clip_skip": 1,
    "repose_preprocessed": False,
    "repose_appearance_path": "",
    "repose_style_preset": "balanced",
    "repose_ip_adapter2_variant": "",
    "repose_ip_adapter2_scale": 0.5,
    "repose_style_ref_path": "",
    # ControlNet tab settings
    "controlnet_mode": "txt2img",
    "controlnet_checkpoint": "",
    "controlnet_sampler": "DPM++ 2M",
    "controlnet_scheduler": "Karras",
    "controlnet_prompt": "",
    "controlnet_negative_prompt": "",
    "controlnet_steps": 20,
    "controlnet_cfg_scale": 7.0,
    "controlnet_seed": -1,
    "controlnet_width": 512,
    "controlnet_height": 512,
    "controlnet_denoising_strength": 0.75,
    "controlnet_type": "canny",
    "controlnet_type2": "",
    "controlnet_strength": 0.8,
    "controlnet_strength2": 0.5,
    "controlnet_source_path": "",
    "controlnet_condition_path": "",
    "controlnet_condition2_path": "",
    "controlnet_mask_path": "",
    "controlnet_batch_count": 1,
    "controlnet_guidance_start": 0.0,
    "controlnet_guidance_end": 1.0,
    "controlnet_guess_mode": False,
    "controlnet_clip_skip": 1,
    "controlnet_preprocessed": False,
    # ControlNet preprocessor params (forwarded as run_preprocessor overrides)
    "cn_canny_low": 100,
    "cn_canny_high": 200,
    "cn_detect_resolution": 512,
    "cn_image_resolution": 512,
    "cn_openpose_include_hand": True,
    "cn_openpose_include_face": True,
    # Longshot settings
    "ls_source_path": "",
    "ls_range_start": 0.0,
    "ls_range_end": 0.0,
    "ls_subdivisions": 4,
    "ls_gapfill_duration": 2.0,
    "ls_final_video_path": "",
    # FLUX generation settings
    "flux_prompt": "",
    "flux_negative_prompt": "",
    "flux_steps": 35,
    "flux_cfg_scale": 3.5,
    "flux_width": 1024,
    "flux_height": 1024,
    "flux_seed": -1,
    "flux_batch_count": 1,
    "flux_denoising_strength": 0.9,
    "flux_max_seq_len": 512,
    "flux_scheduler": "Euler",
    "flux_activated_loras": [],
    "flux_lora_multipliers": "",
    "flux_source_path": "",
    "flux_remove_bg": False,
    "flux_img2img_source_path": "",
    "flux_fill_source_path": "",
    "flux_fill_prompt": "",
    "flux_fill_negative_prompt": "",
    "flux_fill_steps": 50,
    "flux_fill_cfg_scale": 30.0,
    "flux_fill_strength": 1.0,
    "flux_fill_width": 1024,
    "flux_fill_height": 1024,
    "flux_fill_seed": -1,
    "flux_fill_remove_bg": False,
    # Z-Image generation settings
    "zimage_prompt": "",
    # Negative prompt — backend already accepts it (ZIMAGE_STRATEGY.has_negative_prompt).
    "zimage_negative_prompt": "",
    # CFG normalization on/off and truncation threshold for the Z-Image guider.
    "zimage_cfg_normalization": True,
    "zimage_cfg_truncation": 0.0,
    "zimage_steps": 9,
    "zimage_cfg_scale": 0.0,
    "zimage_width": 1024,
    "zimage_height": 1024,
    "zimage_seed": -1,
    "zimage_batch_count": 1,
    "zimage_denoising_strength": 0.7,
    "zimage_remove_bg": False,
    "zimage_activated_loras": [],
    "zimage_lora_multipliers": "",
    "zimage_source_path": "",
    "zimage_inpaint_source_path": "",
    "zimage_inpaint_prompt": "",
    "zimage_inpaint_steps": 9,
    "zimage_inpaint_cfg_scale": 0.0,
    "zimage_inpaint_strength": 1.0,
    "zimage_inpaint_width": 1024,
    "zimage_inpaint_height": 1024,
    "zimage_inpaint_seed": -1,
    "zimage_inpaint_remove_bg": False,
    # Lip Sync settings
    "lipsync_source_path": "",
    "lipsync_audio_path": "",
    "lipsync_result_path": "",
    "lipsync_face_bbox": [],
    "lipsync_steps": 20,
    "lipsync_guidance": 1.5,
    # VACE MultiTalk settings
    "vmt_source_path": "",
    "vmt_audio_left": "",
    "vmt_audio_right": "",
    "vmt_result_path": "",
    "vmt_resolution": "832x480",
    "vmt_steps": 20,
    "vmt_shift": 5.0,
    "vmt_seed": -1,
    "vmt_speaker_bboxes": [],
    "vmt_speaker_assignments": {},
    # Timeline settings
    "tl_library_clips": [],
    "tl_timeline_clips": [],
    "tl_tracks": [],
    "tl_export_settings": {},
    "tl_preview_path": "",
    "tl_fps": 24.0,
    "tl_zoom_start": 0.0,
    "tl_zoom_end": 1.0,
    "tl_versions": {},          # {name: {tracks, markers}} snapshots
    "tl_active_version": "",    # currently loaded version name
    # Color Correct tab settings
    "cc_source_path": "",
    "cc_ref_path": "",
    "cc_strength": 1.0,
    "cc_histogram_match": False,
    "cc_result_path": "",
    # Brightness/Contrast tab settings
    "bc_source_path": "",
    "bc_ref_path": "",
    "bc_brightness": 1.0,
    "bc_contrast": 1.0,
    "bc_strength": 1.0,
    "bc_mode": 0,
    "bc_result_path": "",
    # Hue/Saturation tab settings
    "hs_source_path": "",
    "hs_ref_path": "",
    "hs_hue_shift": 0.0,
    "hs_saturation": 1.0,
    "hs_strength": 1.0,
    "hs_mode": 0,
    "hs_result_path": "",
    # Speed Control tab settings
    "sc_source_path": "",
    "sc_preset_idx": 4,
    "sc_result_path": "",
    # Chatterbox TTS settings
    "chatterbox_text": "",
    "chatterbox_ref_audio": "",
    "chatterbox_exaggeration": 0.5,
    "chatterbox_cfg_weight": 0.5,
    # SadTalker (audio-driven talking head)
    "sadtalker_source_path": "",
    "sadtalker_audio_path": "",
    "sadtalker_preprocess": "extfull",
    "sadtalker_size": 256,
    "sadtalker_pose_style": 0,
    "sadtalker_exp_scale": 1.0,
    "sadtalker_still_mode": False,
    "sadtalker_use_blink": True,
    "sadtalker_batch_size": 2,
    "sadtalker_enhancer_method": "None",
    "sadtalker_background_enhancer": False,
    "sadtalker_ref_video": "",
    "sadtalker_ref_info": "pose+blink",
    "sadtalker_use_ref_video": False,
    "sadtalker_use_idle_mode": False,
    "sadtalker_length_of_audio": 5,
    "sadtalker_input_yaw_str": "",
    "sadtalker_input_pitch_str": "",
    "sadtalker_input_roll_str": "",
    "sadtalker_face3dvis": False,
    "sadtalker_result_path": "",
    # MimicMotion (pose-driven body animation)
    "mimicmotion_reference_path": "",
    "mimicmotion_driving_path": "",
    "mimicmotion_audio_path": "",
    "mimicmotion_result_path": "",
    "mimicmotion_resolution": "512x896",
    "mimicmotion_num_frames": 72,
    "mimicmotion_steps": 25,
    "mimicmotion_guidance": 3.0,
    "mimicmotion_seed": -1,
    "mimicmotion_fps": 24,
    "mimicmotion_min_guidance": 1.0,
    "mimicmotion_max_guidance": 3.0,
    "mimicmotion_noise_aug": 0.02,
    "mimicmotion_pose_align": True,
}

DEFAULTS = {
    "global": GLOBAL_DEFAULTS,
    "project": PROJECT_DEFAULTS,
}
